(define (double a) (* a 2))
(define (halve a) (/ a 2))
(define (even? n)
  (= (remainder n 2) 0))
(define (fast-* b n)
  (cond ((= n 0) 0)
        ((= n 1) b)
        ((= n 2) (double b))
        ((even? n) (double (fast-* b (halve n))))
        (else (+ b (fast-* b (- n 1))))))

(print (fast-* 4 5))
(print (fast-* 3 9))
(print (fast-* 3 8))
(print (fast-* 5 1))
(print (fast-* 3 3))
(print (fast-* 2 3))
(print (fast-* 3 7))
(print (fast-* 3 6))
(print (fast-* 3 5))
